name: TeamAssign
version: ${project.version}
main: teamassign.teamassign.TeamAssign
api-version: 1.13
commands:
  teamassign:
    aliases:
      - ta
    permission: ta.admin
permissions:
  ta.admin:
    description: Allows you to use commands to this plugin
